spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


slack:
  bot:
    token: 토큰
  user:
    token: 토큰
