spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  flyway:
    enabled: true
  h2:
    console:
      enabled: true

common:
  password: 1234

slack:
  user:
    token: 토큰
  bot:
    token: 토큰
